### ISSUE TITLE
Thread computing seems completely off

### ISSUE THREAD

**Issue by mildred** [stalwartlabs/jmap-server#39] opened 2023-03-02 00:08 UTC
When querying a thread, it seems the thread computation is completely off. I get many unrelated messages bundleled up in the thread.

For example I have a thread with two mails, with the following headers:

```
Subject:
 =?utf-8?B?UsOpcG9uc2UgYXV0b21hdGlxdWXCoDogUHJvYmzDqG1lIHN1ciBsJ0lDViBF?=
 =?utf-8?Q?IMEv6_de_"Polycarbonate_granulate_(PC);_EU-28"?=
Thread-Topic:
 =?utf-8?B?UHJvYmzDqG1lIHN1ciBsJ0lDViBFSU1FdjYgZGUgIlBvbHljYXJib25hdGUg?=
 =?utf-8?Q?granulate_(PC);_EU-28"?=
Thread-Index: AQHZQGDw1yDTBdy3L0maSZD17joCnK7OQSBz
Date: Tue, 14 Feb 2023 10:41:49 +0000
Message-ID:
 <16f7ee229cf740efbdb702f67c7bad2f@DU2PR05MB8824.eurprd05.prod.outlook.com>
References: <42889b6e-b6a0-0822-81bf-90c40a7e51e6@mildred.fr>
In-Reply-To: <42889b6e-b6a0-0822-81bf-90c40a7e51e6@mildred.fr>
```

```
Subject: ** PROBLEM Service Alert: example.org/Postfix Queue is WARNING **
Message-Id: <20230217123910.64BD588B97@apex.rezine.org>
Date: Fri, 17 Feb 2023 13:39:10 +0100 (CET)
```

The messages do not share a message-id, the subject is completely different. Those message should not be in the same thread.

Note that in the second message, the Thread-Index and Thread-Topic headers are missing

**Comment by mdecimus** [comment] 2023-03-02 15:12
This is a duplicate of https://github.com/stalwartlabs/jmap-server/issues/34

**Closed by mdecimus** 2023-03-02 15:12 UTC
